USE SWABHAV;

-- STORED PROCEDURE WITHOUT PARAMETER
DELIMITER //
CREATE PROCEDURE SP_GETALL()
BEGIN
	
	SELECT * FROM EMP;
END //
DELIMITER ;

CALL SP_GETALL();

-- STORED PROCEDURE WITH PARAMETER
-- DEFAULT INPUT PAARAMETER IS INPUT PARAMETER SO IN CAN BE IGNORED WHILE WRITING
DELIMITER //
CREATE PROCEDURE SP_GETWITHID( IN ID INT)
BEGIN
	
	SELECT * FROM EMP WHERE EMPNO=ID;
END //
DELIMITER ;

CALL SP_GETWITHID(7900);

--  VIEWING STORED PROCEDURES
SHOW PROCEDURE STATUS;
SHOW PROCEDURE STATUS WHERE NAME LIKE 'S%';
SHOW PROCEDURE STATUS WHERE DB LIKE 'S%';
