USE TRIGGERCHECK;

CREATE TABLE EMP(ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(20),AGE INT);

CREATE TABLE EMP_AUDIT( ID INT PRIMARY KEY AUTO_INCREMENT, AUDIT_DESC VARCHAR(200));

DELIMITER //
CREATE TRIGGER TR_AFTERINSERTEMP
AFTER INSERT ON EMP
FOR EACH ROW
BEGIN
	
    INSERT INTO EMP_AUDIT VALUES(NULL, CONCAT(' a NEW ROW IS INSERTED AT ',DATE_FORMAT(NOW(), '%D-%M-%Y %H:%I:%S %P')));
    
END; //
DELIMITER ;

INSERT INTO EMP VALUES(NULL, 'GAYATRI', 21);

SELECT * FROM EMP_AUDIT;

