USE SWABHAV;
CREATE TABLE CUSTOMER(CID INT, CNAME VARCHAR(10));
INSERT INTO CUSTOMER(CID, CNAME) VALUES(1,'Gayatri'),(2,'DEEPAK'),(3,'SHIVAM'),(4,'NIKHIL'),(5,'RAJ'),(6,'GAURAV'),(7,'SHRUTI');
UPDATE CUSTOMER SET CNAME='GAYATRI' WHERE CID=1;
DELETE FROM CUSTOMER WHERE CID=7;
SELECT * FROM CUSTOMER;