USE SWABHAV;

CREATE TABLE FOO(ID INT, DESCRIPTION VARCHAR(20));

INSERT INTO FOO VALUES(100, "ADDING 100");

INSERT INTO FOO VALUES(10, "ADDING 10");

INSERT INTO FOO VALUES(50, "ADDING 50");

INSERT INTO FOO VALUES(5, "ADDING 5");

SELECT * FROM FOO;

ALTER TABLE FOO
ADD PRIMARY KEY(ID);

SELECT * FROM FOO;