USE SHOPPING;
CREATE TABLE CUSTOMER(CID INT, CNAME VARCHAR(10), PRIMARY KEY (CID));
INSERT INTO CUSTOMER(CID, CNAME) VALUES(1,'Gayatri'),(2,'DEEPAK'),(3,'SHIVAM'),(4,'NIKHIL'),(5,'RAJ'),(6,'GAURAV');
SELECT * FROM CUSTOMER;