USE SHOPPING;
CREATE TABLE LINEITEM(LID INT, QTY INT,OID INT, PRIMARY KEY (LID), FOREIGN KEY(OID) REFERENCES ORDERS(OID));
INSERT INTO LINEITEM(LID, QTY, OID) VALUES(1,2,1),(2,3,2);
SELECT * FROM LINEITEM;