USE SHOPPING;
CREATE TABLE ORDERS(OID INT, ODATE VARCHAR(10),CID INT, PRIMARY KEY (OID), FOREIGN KEY(CID) REFERENCES CUSTOMER(CID));
INSERT INTO ORDERS(OID, ODATE, CID) VALUES(1,'1/7/2021',1),(2,'10/7/2021',1);
SELECT * FROM ORDERS;