USE SHOPPING;
CREATE TABLE PRODUCT(PID INT, PNAME VARCHAR(10),PCOST INT,LID INT, PRIMARY KEY (PID), FOREIGN KEY(LID) REFERENCES LINEITEM(LID));
INSERT INTO PRODUCT(PID, PNAME, PCOST, LID) VALUES(1,'PEN',12,1),(2,'BOOK',60,2),(3,'CHOCOLATE',45,1);
SELECT * FROM PRODUCT;