USE TRANSACTION;

CREATE TABLE CUSTOMER(ID INT, NAME VARCHAR(10),BAL INT);

CREATE TABLE MERCHANT(ID INT, NAME VARCHAR(10),BAL INT);

INSERT INTO CUSTOMER VALUES(1,'AB',3000);
INSERT INTO CUSTOMER VALUES(2,'DE',900);
INSERT INTO CUSTOMER VALUES(10,'GH',5000);
INSERT INTO CUSTOMER VALUES(11,'GHJ',7000);
INSERT INTO CUSTOMER VALUES(12,'MN',4000);
DELETE FROM CUSTOMER WHERE ID IN (10,11,12);
UPDATE CUSTOMER SET NAME='C1' WHERE ID=1;
UPDATE CUSTOMER SET NAME='C2' WHERE ID=2;

INSERT INTO MERCHANT VALUES(1,'AB',10000);
INSERT INTO MERCHANT VALUES(2,'DE',5000);
INSERT INTO MERCHANT VALUES(10,'GH',0);
INSERT INTO MERCHANT VALUES(11,'GHJ',0);
INSERT INTO MERCHANT VALUES(12,'MN',0);

UPDATE MERCHANT SET NAME='M1' WHERE ID=1;
UPDATE MERCHANT SET NAME='M2' WHERE ID=2;
DELETE FROM MERCHANT WHERE ID IN (10,11,12);


SELECT * FROM CUSTOMER;

SELECT * FROM MERCHANT;
