USE UNIVERSITY;
CREATE TABLE PROFESSOR(PID INT, PNAME VARCHAR(10),DID INT, PRIMARY KEY(PID), FOREIGN KEY(DID) REFERENCES DEPARTMENT(DID));
INSERT INTO PROFESSOR(PID, PNAME, DID) VALUES(1,'KANNAN',1),(2,'TEJAL',2);
SELECT * FROM PROFESSOR;